#!/usr/bin/env python
import sys
from spacefuck.parser import SFParser
from spacefuck.interpreter import SFInterpreter

if __name__ == '__main__':
    p = SFParser.from_file(sys.argv[1])
    t = p.get_tokens()

    i = SFInterpreter()
    i.execute(t)

    print
